ALTER TABLE users
ADD COLUMN avatar_url VARCHAR(1000) NULL,
ADD COLUMN avatar_public_id VARCHAR(255) NULL,
ADD COLUMN phone VARCHAR(20) NULL,
ADD COLUMN school_name VARCHAR(100) NULL,
ADD COLUMN major VARCHAR(100) NULL,
ADD COLUMN student_code VARCHAR(100) NULL,
ADD COLUMN graduation_year INT NULL,
ADD COLUMN education_level VARCHAR(50) NULL,
ADD COLUMN bio VARCHAR(500) NULL;
