package com.demo.ai_study_hub;

import com.demo.ai_study_hub.config.VNPayProperties;
import com.demo.ai_study_hub.service.VNPayService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.LinkedHashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class VNPayServiceTest {

    private VNPayService vnPayService;
    private VNPayProperties props;

    @BeforeEach
    void setUp() {
        props = new VNPayProperties();
        props.setEnabled(true);
        props.setTmnCode("TESTTMN01");
        props.setHashSecret("SECRETKEYFORTESTONLY123456");
        props.setPaymentUrl("https://sandbox.vnpayment.vn/paymentv2/vpcpay.html");
        props.setReturnUrl("https://example.com/api/payments/vnpay/return");
        props.setIpnUrl("https://example.com/api/payments/vnpay/ipn");

        vnPayService = new VNPayService(props);
    }

    // =========================================================================
    // buildPaymentUrl / verifyChecksum — signature must be internally consistent
    // even with spaces/special chars in orderInfo or the returnUrl.
    // =========================================================================

    @Test
    void buildPaymentUrl_ShouldProduceUrlWithSecureHash() {
        String url = vnPayService.buildPaymentUrl(
                "PAYTEST123", 199000L, "Payment for order 1",
                "127.0.0.1", null, "vn",
                LocalDateTime.now(ZoneOffset.UTC).plusMinutes(15));

        assertTrue(url.startsWith(props.getPaymentUrl() + "?"));
        assertTrue(url.contains("vnp_SecureHash="));
        assertTrue(url.contains("vnp_TxnRef=PAYTEST123"));
        assertTrue(url.contains("vnp_Amount=19900000")); // *100 per VNPay spec
    }

    @Test
    void buildPaymentUrl_ThenVerifyChecksum_ShouldRoundTripCorrectly_WithSpacesInOrderInfo() {
        // orderInfo contains a space — this is exactly the case that broke
        // signing when hashData used raw (non-encoded) values.
        String orderInfo = "Payment for order 42 upgrade to Premium";
        String url = vnPayService.buildPaymentUrl(
                "PAYTEST42", 399000L, orderInfo,
                "203.0.113.5", "NCB", "vn",
                LocalDateTime.now(ZoneOffset.UTC).plusMinutes(15));

        Map<String, String> params = parseQueryParams(url);
        assertTrue(vnPayService.verifyChecksum(params),
                "A signature generated by buildPaymentUrl must always verify successfully");
    }

    @Test
    void verifyChecksum_WhenHashTampered_ShouldFail() {
        String url = vnPayService.buildPaymentUrl(
                "PAYTEST99", 199000L, "Payment for order 99",
                "127.0.0.1", null, "vn",
                LocalDateTime.now(ZoneOffset.UTC).plusMinutes(15));

        Map<String, String> params = parseQueryParams(url);
        params.put("vnp_Amount", "99999900"); // tamper with amount after signing

        assertFalse(vnPayService.verifyChecksum(params));
    }

    @Test
    void verifyChecksum_WhenSecureHashMissing_ShouldFail() {
        Map<String, String> params = new LinkedHashMap<>();
        params.put("vnp_TxnRef", "PAYTEST1");
        params.put("vnp_Amount", "19900000");
        // no vnp_SecureHash at all

        assertFalse(vnPayService.verifyChecksum(params));
    }

    @Test
    void verifyChecksum_WhenReturnUrlHasSpecialChars_ShouldStillRoundTrip() {
        props.setReturnUrl("https://example.com/api/payments/vnpay/return?env=sandbox&x=1 2");
        VNPayService service = new VNPayService(props);

        String url = service.buildPaymentUrl(
                "PAYTESTSPECIAL", 199000L, "Order with special chars: 100%",
                "127.0.0.1", null, "vn",
                LocalDateTime.now(ZoneOffset.UTC).plusMinutes(15));

        Map<String, String> params = parseQueryParams(url);
        assertTrue(service.verifyChecksum(params));
    }

    // =========================================================================
    // parsePayDateToUtc
    // =========================================================================

    @Test
    void parsePayDateToUtc_WhenValidFormat_ShouldConvertVnTimeToUtc() {
        // 2026-07-06 14:30:00 Asia/Ho_Chi_Minh (UTC+7) -> 2026-07-06 07:30:00 UTC
        LocalDateTime result = vnPayService.parsePayDateToUtc("20260706143000");

        assertNotNull(result);
        assertEquals(LocalDateTime.of(2026, 7, 6, 7, 30, 0), result);
    }

    @Test
    void parsePayDateToUtc_WhenMalformed_ShouldReturnNull() {
        assertNull(vnPayService.parsePayDateToUtc("not-a-date"));
        assertNull(vnPayService.parsePayDateToUtc(""));
        assertNull(vnPayService.parsePayDateToUtc(null));
    }

    // =========================================================================
    // Bank code allowlist
    // =========================================================================

    @Test
    void isValidBankCode_ShouldAllowNullOrBlank() {
        assertTrue(vnPayService.isValidBankCode(null));
        assertTrue(vnPayService.isValidBankCode(""));
    }

    @Test
    void isValidBankCode_ShouldAllowListedCodes() {
        assertTrue(vnPayService.isValidBankCode("NCB"));
        assertTrue(vnPayService.isValidBankCode("vnbank"));
    }

    @Test
    void isValidBankCode_ShouldRejectUnknownCode() {
        assertFalse(vnPayService.isValidBankCode("FAKEBANK"));
    }

    // =========================================================================
    // Helper: parse a VNPay URL's query string back into a param map, the
    // same way an IPN/Return handler would receive it from Spring.
    // =========================================================================
    private Map<String, String> parseQueryParams(String url) {
        String query = url.substring(url.indexOf('?') + 1);
        Map<String, String> params = new LinkedHashMap<>();
        for (String pair : query.split("&")) {
            String[] kv = pair.split("=", 2);
            String key = java.net.URLDecoder.decode(kv[0], java.nio.charset.StandardCharsets.UTF_8);
            String value = kv.length > 1
                    ? java.net.URLDecoder.decode(kv[1], java.nio.charset.StandardCharsets.UTF_8)
                    : "";
            params.put(key, value);
        }
        return params;
    }
}