# Đè cấu hình kết nối sang H2 database chạy trên RAM khi test
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cấu hình Hibernate Dialect cho H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Giả lập Email không gửi thật
spring.mail.host=localhost

# Điền giá trị giả lập cố định để Spring Boot không đi tìm biến môi trường khi chạy test
GMAIL_USERNAME=mock-email@gmail.com
GMAIL_APP_PASSWORD=mockpassword